export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAIL = 'LOG_IN_FAIL';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';
export const RESET_SESSION = 'RESET_SESSION';
export const FETCH_USER_INFO = 'FETCH_USER_INFO';
export const FETCH_SEARCH_RESULTS = 'FETCH_SEARCH_RESULTS';
export const EMPTY_SEARCH_RESULTS = 'EMPTY_SEARCH_RESULTS';
